//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoneFiveSoftware.SportTracks.Device.BT747.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZoneFiveSoftware.SportTracks.Device.BT747.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import new data only.
        /// </summary>
        public static string DeviceConfigurationDlg_chkImportOnlyNew_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_chkImportOnlyNew_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port:.
        /// </summary>
        public static string DeviceConfigurationDlg_portConfig_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_portConfig_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track change (min):.
        /// </summary>
        public static string DeviceConfigurationDlg_tracChange_Text {
            get {
                return ResourceManager.GetString("DeviceConfigurationDlg_tracChange_Text", resourceCulture);
            }
        }
        
        public static System.Drawing.Bitmap Image_48_BT747 {
            get {
                object obj = ResourceManager.GetObject("Image_48_BT747", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
